

- name: installing mysql
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql
    ansible.builtin.dnf:
      name: mysql-server
      state: present

  - name: starting mysqld services
    ansible.builtin.service:
      name: mysqld
      state: restarted
      enabled: yes  
      
  - name: adding system user
    ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1       